### PR TITLE
Wild ) missing

### PR DESCRIPTION
**Pull request by RazvanBudacaTechquarter**
Don't panic, I got dis.

### CODE REVIEW

**Comment by jeinygroove** [comment]
Already fixed it in #17

**Comment by jeinygroove** [comment]
Are you building project before doing `git push`?

**Review by jeinygroove — APPROVED** [review]

**Comment by RazvanBudacaTechquarter** [comment]
> Are you building project before doing `git push`?

I got hasty this time.

**Comment by jeinygroove** [comment]
> I got hasty this time.

It's a good practice to build project before each commit, in intellij it takes a few seconds for example

**Pull request merged**
