### PR TITLE
Display interpretation of sentiment analysis

### PR DESCRIPTION
**Pull request by jeinygroove**

### CODE REVIEW

**Review by RazvanBudacaTechquarter — APPROVED** [review]
Best PR ever

**Review by jgaillard85 — COMMENTED** [review]
I know it is very simple, but could you deploy this please? I would like to see it in action just to be sure

**Comment by jeinygroove** [comment]
> I know it is very simple, but could you deploy this please? I would like to see it in action just to be sure

Just noticed a small bug on backend, someone forgot to add interpretation to the AnalysisInfo object, fixing... It's deployed, but will display non empty interpretation only for searched songs, not songs in the rating list.

**Comment by RazvanBudacaTechquarter** [comment]
> > I know it is very simple, but could you deploy this please? I would like to see it in action just to be sure
> 
> Just noticed a small bug on backend, someone forgot to add interpretation to the AnalysisInfo object, fixing... It's deployed, but will display non empty interpretation only for searched songs, not songs in the rating list.

Yep, that's my bad. I only added the interpretation in the SongSentiment object.

**Comment by jeinygroove** [comment]
> > > I know it is very simple, but could you deploy this please? I would like to see it in action just to be sure
> > 
> > 
> > Just noticed a small bug on backend, someone forgot to add interpretation to the AnalysisInfo object, fixing... It's deployed, but will display non empty interpretation only for searched songs, not songs in the rating list.
> 
> Yep, that's my bad. I only added the interpretation in the SongSentiment object.

I think it's wasn't a good idea to add these exact fields to analysisInfo class, you should've added just SongSentiment field instead, so we won't need to copy-paste new fields each time. I will make an issue for that)

**Review by jgaillard85 — APPROVED** [review]

**Pull request merged**
